import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000, // 👈 applies to all toasts by default
            style: {
              fontSize: "14px",
              padding: "12px 16px",
            },
            success: {
              duration: 2500, // 👈 override for success
              style: {
                background: "black",
                color: "white",
              },
            },
            error: {
              duration: 4000, // 👈 override for error
              style: {
                background: "#ef4444",
                color: "white",
              },
            },
          }}
        /> */}
        <ToastContainer position="top-right" autoClose={3000}></ToastContainer>

        {children}
      </body>
    </html>
  );
}
